---
title: 'DS 202: Lab 5'
author: "Muhammad Khairi Norizan"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
# Load Data set
accident <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
person <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
```

## Question 1
Create a data frame containing the persons who are fatally hurt in the accidents (see FARS manual and look up variable `INJ_SEV`)

## Question 2
Create a data frame containing the most dangerous vehicle make in each state. The number of persons fatally hit in the vehicle make is used to assess the non-safety of a make. Make sure to handle the missing values appropriately. (look up variable `MAKE`)

## Question 3
Create a map, and label each state with the most dangerous vehicle. Discuss the definition of the most dangerous vehicle, and what you find from the map. (Hint: Read the description for the `STATE` and `COUNTY` columns in the FARS manual. The state & county codes are Geographic Locator Codes (GLCs) from the General Services Administration's (GSA) publication. Use `readxl::read_xlsx` to read in the GLCs.)

## Question 4
Join the accident and person table (work out which variable(s) to use)

## Question 5
Tally the number of accidents by day of the week (`DAY_WEEK`), hour of the day (`HOUR`) and gender (`SEX`). Visualize the results and explain what you find.

## Question 6
Now plot a choropleth map of the number of deaths on a county level. Also explain what you find. 
